[package]

name = "astronomical"
version = "0.1.0"
authors = [
    "Morgan <clicker@morganhe.in>",
]

[[bin]]
name = "astronomical"

[dependencies]
find_folder = "0.3.0"
update_rate = "1.0"
rand = "0.5"
amethyst = "0.8.0"